version: "3.9"

networks:
  macvlan10:
    external: true

volumes:
  pihole:
    external: true
  pihole-dnsmasq:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      macvlan20:
        ipv4_address: 192.168.0.10
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
      #- 443/tcp
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'password'
      #INTERFACE: 'eno1.10'
      #DNSMASQ_LISTENING: 'eno1.10'
      ServerIP: '192.168.0.10'
      DNS1: '9.9.9.9'
      DNS2: '1.1.1.1'
      DNSSEC: 'true'
      #DNS_BOGUS_PRIV: 'false'
      #DNS_FQDN_REQUIRED: 'true'
      VIRTUAL_HOST: 'pihole.domain.com'
      WEB_PORT: 80
      #DNSMASQ_USER: 'pihole' - causes dnsmasq not to start
      TEMPERATUREUNIT: 'f'
    volumes:
      - pihole:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 9.9.9.9
    #cap_add:
      #- NET_ADMIN - only needed when using the dhcp server
    restart: unless-stopped
